#pragma once
// Auto-generated by CMake; do not edit directly.

#ifndef CADMUS_RHI_API
# if defined(_WIN32)
#  if defined(CADMUS_RHI_BUILD_DLL)
#   define CADMUS_RHI_API __declspec(dllexport)
#  elif defined(CADMUS_RHI_USE_DLL)
#   define CADMUS_RHI_API __declspec(dllimport)
#  else
#   define CADMUS_RHI_API
#  endif
# elif defined(__GNUC__) && __GNUC__ >= 4
#  if defined(CADMUS_RHI_BUILD_DLL)
#   define CADMUS_RHI_API __attribute__((visibility("default")))
#  else
#   define CADMUS_RHI_API
#  endif
# else
#  define CADMUS_RHI_API
# endif
#endif


#ifndef FORCE_INLINE
#ifdef _MSC_VER
#define FORCE_INLINE __forceinline
#elif ( (defined(__GNUC__) && (__GNUC__ >= 4)) || defined(__clang__) )
#define FORCE_INLINE __attribute__((always_inline)) static __inline__
#else
#define FORCE_INLINE static SDL_INLINE
#endif
#endif /* SDL_FORCE_INLINE not defined */
