#pragma once
// Auto-generated by CMake; do not edit directly.

#ifndef CADMUS_RHI_API
# if defined(_WIN32)
#  if defined(CADMUS_RHI_BUILD_DLL)
#   define CADMUS_RHI_API __declspec(dllexport)
#  elif defined(CADMUS_RHI_USE_DLL)
#   define CADMUS_RHI_API __declspec(dllimport)
#  else
#   define CADMUS_RHI_API
#  endif
# elif defined(__GNUC__) && __GNUC__ >= 4
#  if defined(CADMUS_RHI_BUILD_DLL)
#   define CADMUS_RHI_API __attribute__((visibility("default")))
#  else
#   define CADMUS_RHI_API
#  endif
# else
#  define CADMUS_RHI_API
# endif
#endif
